### ISSUE TITLE
The bot isn't editing the blank message

### ISSUE THREAD

**Issue by devilish-crow** [EnriqueMoran/remoteDiscordShell#15]
I only receive blank messages from the bot, it isn't editing them. Same bug as #13 
![2023-03-02-215518_1920x1080_scrot](https://user-images.githubusercontent.com/126820517/222538352-f4577498-4b56-4410-ada8-713bdb42e8b1.png)

**Comment by CoomInPickle** [comment]
did u fix it? i have the same issue

**Comment by bing0o** [comment]
same issue, any fix yet?
![Screenshot 2023-06-26 123055](https://github.com/EnriqueMoran/remoteDiscordShell/assets/25457545/8d579a83-eb46-4a96-9939-2c2584f05f16)

**Comment by CoomInPickle** [comment]
Yes, in the discord dev portal go to your application and then to bot.
Enable this:![Screenshot_2023-06-26-13-46-39-02_2c9606bce337650a539aceea20c7df58.jpg](https://github.com/EnriqueMoran/remoteDiscordShell/assets/98626608/16c2f79e-3215-41e3-a607-37dd6893f023)

**Comment by bing0o** [comment]
@CoomInPickle thanks bro, it worked!
