### ISSUE TITLE
Feature Request: change the behaviour for when a message is longer than 2000 words

### ISSUE THREAD

**Issue by joeydoesthings** [EnriqueMoran/remoteDiscordShell#8]
Rather than edit out everything and replace it by saying

400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.

Make it start a new message so if something is longer it still gets displayed

**Comment by EnriqueMoran** [comment]
Fixed in 84ffd74ea3e823c5ecfb2621f4a29f16328af735!
